sbxw/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'sbxw.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^ui/', include('ui.urls', namespace="ui")),
    url(r'^admin/', include(admin.site.urls)),
)

ui/urls.py
from django.conf.urls import patterns, url

from ui import views

urlpatterns = patterns('',
    # ex: /ui/
    url(r'^$', views.index, name='index'),
    # ex: /ui/index?host=5
    url(r'^index$', views.index, name='index'),
    # ex: /ui/5/
    url(r'^(?P<title_id>\d+)/$', views.webtitledetail, name='webtitledetail'),
    # ex: /ui/image/5
    url(r'^image/(?P<image_id>\d+)$', views.webimagedetail, name='webimagedetail')
)

ui/models.py
from django.db import models

# Create your models here.
class Host(models.Model):
    ip = models.GenericIPAddressField()
    mac = models.CharField(max_length=48, null=True)
    hostname = models.CharField(max_length=255, null=True)

class Webrequest(models.Model):
    host = models.ForeignKey(Host)
    server = models.CharField(max_length=255)
    port = models.IntegerField()
    url = models.CharField(max_length=2048)
    t = models.DateTimeField(auto_now=True)
    istitle = models.BooleanField(default=False)
    isimage = models.BooleanField(default=False)
    issearch = models.BooleanField(default=False)
    isnetflix = models.BooleanField(default=False)
    
    def adrequest(self):
        if (self.server == "ad.doubleclick.net" or self.server == "us-u.openx.net" or 
            self.server == "mf.sitescout.com" or self.server == "ads.adsonar.com" or
            self.server == "view.atdmt.com" or self.server == "imp.bid.ace.advertising.com" or
            self.server == "platform.twitter.com" or self.server == "rad.msn.com" or
            self.server == "web.adblade.com" or self.server == "ct1.addthis.com" or
            self.server == "googleads.g.doubleclick.net" or self.server == "aax-us-west.amazon-adsystem.com" or
            self.server == "aax-us-east.amazon-adsystem.com" or self.server == "apis.google.com" or
            self.server == "a-us-atl.netmng.com"):
            return True
        else:
            return False
        

class Webimage(models.Model):
    webrequest = models.ForeignKey(Webrequest)
    sourcerequest = models.ForeignKey(Webrequest, related_name='images', null=True)
    md5 = models.CharField(max_length=48, null=True)
    filename = models.CharField(max_length=255, null=True)
    thumbnailfilename = models.CharField(max_length=255, null=True)
    tone = models.FloatField(null=True)
    height = models.IntegerField()
    width = models.IntegerField()
    nudity = models.NullBooleanField()
    nudity_confidence = models.IntegerField(null=True)

    def bigenough(self):
        if self.height >= 150 and self.width >= 150:
            return True
        else:
            return False
    
class Webtitle(models.Model):
    webrequest = models.OneToOneField(Webrequest, related_name='title')
    title = models.CharField(max_length=2048)
    

class Websearch(models.Model):
    webrequest = models.OneToOneField(Webrequest, related_name='websearch')
    query = models.CharField(max_length=2048)
    
class Webnetflix(models.Model):
    webrequest = models.OneToOneField(Webrequest, related_name='netflix')
    title = models.CharField(max_length=512)
    rating = models.CharField(max_length=10, null=True)
    plot = models.CharField(max_length=2048, null=True)
    poster = models.CharField(max_length=2048, null=True)
    imdbid = models.CharField(max_length=32, null=True)

ui/forms.py
AVATAR_CHOICES = (('1','option1'), ('2','option2'), ('3','option3'), 
('4','option4'))

class RegistrationForm(forms.Form):
    avatar = ChoiceField(widget=RadioSelect, choices=AVATAR_CHOICES)

ui/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.db.models import Q 
import datetime, pytz

from ui.models import Webrequest, Webtitle, Websearch, Webimage, Webnetflix, Host

def index(request):
            
    hosts = Host.objects.all()
    
    timeframes = (('All time',0),('Today',1),('Yesterday',2),('This Week',3))
    
    # host_id of 0 shows all computers on network
    if request.GET.get('host',''):
        host_id = int(request.GET.get('host'))
    else:
        host_id = 0
    
    if host_id >= 0 and host_id < 25:
        # If it is 0-25, set it on session
        request.session['filteredhost'] = host_id
                
    if 'filteredhost' in request.session and int(request.session.get('filteredhost')) > 0 and int(request.session.get('filteredhost')) < 25:
        # Filter all lists down to only requests that came from single host_id
        filteredhost = int(request.session['filteredhost'])
        
        unsorted_dupes = Webrequest.objects.filter(Q(istitle=True) | Q(images__isnull=False)).filter(host_id=filteredhost)
        latest_search_list = Websearch.objects.filter(webrequest__host_id=filteredhost).order_by('id')
        latest_skintone_image_list = Webimage.objects.filter(height__gte=150).filter(width__gte=150).filter(tone__gte=35).filter(webrequest__host_id=filteredhost).order_by('id')
        latest_netflix_list = Webnetflix.objects.filter(webrequest__host_id=filteredhost).order_by('id')
    else:
        # No filter on hosts
        filteredhost = 0

        # convert list of dupes to a set to remove dupes, then return a list
        unsorted_dupes = Webrequest.objects.filter(Q(istitle=True) | Q(images__isnull=False))    
        latest_search_list = Websearch.objects.order_by('webrequest__t')
        latest_skintone_image_list = Webimage.objects.filter(height__gte=150).filter(width__gte=150).filter(tone__gte=35).order_by('webrequest__t')
        latest_netflix_list = Webnetflix.objects.order_by('webrequest__t')
    
    # timeframe of 0 shows all time
    if request.GET.get('timeframe',''):
        timeframe = int(request.GET.get('timeframe'))
    elif 'timeframe' in request.session:
        timeframe = int(request.session.get('timeframe'))
    else:
        # If its not in the request and not in the session, default to today only
        timeframe = 1
        
    
    if timeframe >= 0 and timeframe <= 3:
        # If it is 0-3, set it on session
        request.session['timeframe'] = timeframe
        
    if 'timeframe' in request.session and int(request.session.get('timeframe')) >= 1 and int(request.session.get('timeframe')) <= 3:
        # If 1, filter to today only.  If 2, filter to yesterday only, If 3, filter to this week.  If 0, no filter.
        timeframe = int(request.session['timeframe'])
        local_tz = pytz.timezone('America/Los_Angeles')
        
        if timeframe is 1:
            gte = datetime.datetime.now(tz=local_tz).replace(hour=0,minute=0,second=0)   
            lte = datetime.datetime.now(tz=local_tz)         
        if timeframe is 2:
            lte = datetime.datetime.now(tz=local_tz).replace(hour=0,minute=0,second=0)           
            gte = lte - datetime.timedelta(days=1)
        if timeframe is 3:
            today = datetime.datetime.now(tz=local_tz).replace(hour=0,minute=0,second=0)
            numberofdaystosubtract = today.weekday() + 1
            gte = today - datetime.timedelta(days=numberofdaystosubtract)
            lte = datetime.datetime.now(tz=local_tz)         
            
        unsorted_dupes = unsorted_dupes.filter(t__gte=gte).filter(t__lte=lte)
        latest_search_list = latest_search_list.filter(webrequest__t__gte=gte).filter(webrequest__t__lte=lte)
        latest_netflix_list = latest_netflix_list.filter(webrequest__t__gte=gte).filter(webrequest__t__lte=lte)
        latest_skintone_image_list = latest_skintone_image_list.filter(webrequest__t__gte=gte).filter(webrequest__t__lte=lte)
        
    # eliminate dupes by converting to set, converting back to list, then sorting (might be better way out there..)
    unsorted_no_dupes = list(set(unsorted_dupes))
    istitle_or_hasimages_requests = sorted(unsorted_no_dupes, key=lambda x:x.t, reverse=True)
    
    # take the slice as last operation (so we can filter)
    latest_search_list = latest_search_list.reverse()[:50]
    latest_skintone_image_list = latest_skintone_image_list.reverse()[:200]
    
    context = {'timeframes': timeframes, 'startingtimecode': timeframe, 'filteredhost': filteredhost, 'istitle_or_hasimages_requests': istitle_or_hasimages_requests, 'hosts': hosts, 'latest_search_list': latest_search_list, 'latest_netflix_list': latest_netflix_list, 'latest_skintone_image_list': latest_skintone_image_list }
    return render(request, 'ui/index.html', context)

def webtitledetail(request, title_id):
    title = get_object_or_404(Webtitle, pk=title_id)
    return render(request, 'ui/webtitledetail.html', {'title': title})

def webimagedetail(request, image_id):
    image = get_object_or_404(Webimage, pk=image_id)
    return render(request, 'ui/webimagedetail.html', {'image': image})

ui/templates/ui/index.html
{% load staticfiles %}

<form action="index">
Show content from: 
<select name="host">
    {% for host in hosts %}
        {% ifequal host.id filteredhost %}
            <option value="{{ host.id }}" selected="selected">{{ host.hostname }}</option>
        {% else %}
            <option value="{{ host.id }}">{{ host.hostname }}</option>
        {% endifequal %}
    {% endfor %}
</select>

<select name="timeframe">
    {% for timeframe,timecode in timeframes %}
        {% ifequal timecode startingtimecode %}
            <option value="{{ timecode }}" selected="selected">Observed {{ timeframe }}</option>
        {% else %}
            <option value="{{ timecode }}">{{ timeframe }}</option>
        {% endifequal %}
    {% endfor %}
</select>

<input type="submit" value="Update!" />
</form>

{% if latest_skintone_image_list %}
    <h1><U>Recent images with high skin tone</U></h1>
    {% for image in latest_skintone_image_list %}
        <a href="{% url 'ui:webimagedetail' image.id %}"><img src="{% static image.thumbnailfilename %}" /></a>
    {% endfor %}
{% else %}
    <p>No images with high skin tone.</P>
{% endif %}    

{% if istitle_or_hasimages_requests %}
    <h1><U>Recent webpages with all images</u></h1>
    <table border=1>
        
    {% for webrequest in istitle_or_hasimages_requests %}
        {% if webrequest.adrequest %}
            <!--<tr><TD>Ad from {{webrequest.server}}</TD><TD>{{ webrequest.t }}</TD><TR>-->
        {% elif webrequest.images.count %}
            {% if webrequest.istitle %}
                <tr><TD><a href="{% url 'ui:webtitledetail' webrequest.title.id %}">{{ webrequest.title.title }} ({{ webrequest.title.id }})</a> - {{webrequest.server }}</TD>
            {% else %}
                <tr><TD>{{ webrequest.url }}</TD>
            {% endif %}
            <TD>{{ webrequest.t }}</TD><TR>
            <TR><TD colspan=2>&nbsp;&nbsp;&nbsp;
            {% for image in webrequest.images.all %}
                <a href="{% url 'ui:webimagedetail' image.id %}"><img src="{% static image.thumbnailfilename %}" /></a>
            {% endfor %}
            </TD>
        {% elif webrequest.istitle %}
            <!-- No images but there is a page title so display this one too. -->
            <tr><TD><a href="{% url 'ui:webtitledetail' webrequest.title.id %}">{{ webrequest.title.title }}</a> - {{ webrequest.server }}</TD><TD>{{ webrequest.t }}</TD><TR>
        {% endif %}  
    {% endfor %}
    </TABLE>
{% else %}
    <p>No recent webpages.</p>
{% endif %}

<HR>
    
{% if latest_search_list %}
    <h1><U>Recent web searches</U></h1>
    <ul>
    {% for search in latest_search_list %}
        <li>{{search.query}}</LI>
    {% endfor %}
    </UL>
{% else %}
    <p>No recent searches.</P>
{% endif %}    

{% if latest_netflix_list %}
    <h1><U>Recent Netflix movies watched</U></h1>
    <table border=1><TR><TD>&nbsp;</TD><TD><B>Title</B></TD><TD><B>Rating</B></TD><TD><B>Watched on</B></TD></TR>
    {% for movie in latest_netflix_list %}
        <TR><TD rowspan=2>
            {% if movie.imdbid %}
                <a href=http://www.imdb.com/title/{{movie.imdbid}}>
            {% endif %}
            {% if movie.poster and movie.poster != "N/A" %}
                <IMG SRC={{movie.poster}} height=150></a>
            {% else %}
                (No poster image)
            {% endif %}
            </TD><TD>
            {% if movie.imdbid %}
                <a href=http://www.imdb.com/title/{{movie.imdbid}}>
            {% endif %}
            {{movie.title}}</a></TD><TD>{{movie.rating}}</TD><TD>{{movie.webrequest.t}} on computer "{{movie.webrequest.host.hostname}}"</TR><TR><TD colspan=3>{{movie.plot}}</TD></TR>
    {% endfor %}
    </TABLE>
{% else %}
    <p>No recent Netflix movies watched.</P>
{% endif %}   
<HR>
    

ui/templates/ui/webimagedetail.html
{% load staticfiles %}

<table border=1>
    <TR><TD>URL:</TD><TD><a href={{image.webrequest.url}}>{{image.webrequest.url}}</a></TD></TR>
    {% if image.sourcerequest %}
        <TR><TD>From webpage:</TD><TD><a href={{image.sourcerequest.url}}>{{image.sourcerequest.url}}</a></TD></TR>
    {% endif %}
    <TR><TD>Size:</TD><TD>{{image.height}}x{{image.width}}</TD></TR>
    <TR><TD>Downloaded:</TD><TD>{{image.webrequest.t}} on computer "{{image.webrequest.host.hostname}}"</TD></TR>
    
</table>

<img src="{% static image.filename %}">

ui/templates/ui/webtitledetail.html
<table border=1>
    <TR><TD>URL:</TD><TD><a href={{title.webrequest.url}}>{{title.webrequest.url}}</a></TD></TR>
    <TR><TD>Title:</TD><TD>{{ title.title }}</TD>
    <TR><TD>Time:</TD><TD>{{title.webrequest.t}}</TD></TR>
</table>
<P><P><P>
<iframe src={{ title.webrequest.url }} width=100% height=100%>